---
title: "Mini-Project 4"
author: "Emily Liu"
date: "April 28, 2018"
output: html_document
---
```{r}
library(mdsr)
library(RMySQL)
db <- dbConnect_scidb(dbname = "citibike")

```

```{r}
test_set <- db %>%
          dbGetQuery("SELECT * 
             FROM trips
             LIMIT 100;")
test_set

test_stations <- db %>%
  dbGetQuery("SELECT *
             FROM station_months;")

test_stations %>%
  distinct(station_id) %>%
  arrange(station_id)


test_stations_sum <- db %>%
  dbGetQuery("SELECT *
             FROM station_summary;")
```

```{r}
# Top 10 stations overall
test_set %>%
  arrange(start_station_id)
test_set %>% 
  select(start_station_id) %>%
  group_by(start_station_id) %>%
  summarize(N = n()) %>%
  arrange(desc(N)) %>%
  head(10)
  
```

```{r}
# Top 10 stations for women
women_10 <- test_set %>% 
  filter(gender == 2) %>%
  select(start_station_id) %>%
  group_by(start_station_id) %>%
  summarize(N = n()) %>%
  arrange(desc(N)) %>%
  head(10)

# Top 10 stations for subscribers
test_set %>% 
  filter(user_type == 'Subscriber') %>%
  select(start_station_id) %>%
  group_by(start_station_id) %>%
  summarize(N = n()) %>%
  arrange(desc(N)) %>%
  head(10)
```

```{r}
top_10_women <- women_10 %>%
  left_join(test_stations_sum, by = c("start_station_id" = "station_id"))

View(top_10_women)
```

```{r}
#finding top 10 start stations overall
db %>%
  dbGetQuery("
SELECT trips.start_station_id,  ss.name, ss.lat, ss.lon, sum(1) AS N
FROM citibike.trips
JOIN citibike.station_summary ss ON trips.start_station_id = ss.station_id
GROUP BY trips.start_station_id
ORDER BY N desc
LIMIT 10;")

#finding top 10 start stations visited by women
db %>%
  dbGetQuery("
SELECT trips.start_station_id,  ss.name, ss.lat, ss.lon, sum(1) AS N
FROM citibike.trips
JOIN citibike.station_summary ss ON trips.start_station_id = ss.station_id
WHERE gender = 2
GROUP BY trips.start_station_id
ORDER BY N desc
LIMIT 10;")
```

```{r}
#finding top 10 most visited stations for everyone
db %>%
  dbGetQuery("
SELECT *, num_starts + num_stops AS visits
FROM citibike.station_summary
JOIN citibike.trips t ON ss.station_id = t.station_id
ORDER BY visits desc
LIMIT 10;")
```

